### ISSUE TITLE
Nodes fail to load in KNIME 3.3.1

### ISSUE THREAD

**Issue by sverhoeven** [3D-e-Chem/knime-kripodb#21]
```
DEBUG : Worker-2 : RepositoryManager :  :  : Node nl.esciencecenter.e3dchem.kripodb.fragmentsbysimilarity.FragmentBySimilarityFactory' from plugin 'nl.esciencecenter.e3dchem.kripodb.plugin' could not be created: 
Can't load factory class for node: nl.esciencecenter.e3dchem.kripodb.fragmentsbysimilarity.FragmentBySimilarityFactory
java.lang.IllegalArgumentException: Can't load factory class for node: nl.esciencecenter.e3dchem.kripodb.fragmentsbysimilarity.FragmentBySimilarityFactory
        at org.knime.workbench.repository.RepositoryFactory.createNode(RepositoryFactory.java:119)
        at org.knime.workbench.repository.RepositoryManager.readNodes(RepositoryManager.java:348)
        at org.knime.workbench.repository.RepositoryManager.readRepository(RepositoryManager.java:165)
        at org.knime.workbench.repository.RepositoryManager.getRoot(RepositoryManager.java:592)
        at org.knime.workbench.repository.view.AbstractRepositoryView.readRepository(AbstractRepositoryView.java:244)
        at org.knime.workbench.repository.view.AbstractRepositoryView$2.run(AbstractRepositoryView.java:228)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.lang.Error: Unresolved compilation problems: 
        Bound mismatch: The type FragmentBySimilarityModel is not a valid substitute for the bounded parameter <T extends NodeModel> of the type NodeFactory<T>
        Bound mismatch: The type FragmentBySimilarityModel is not a valid substitute for the bounded parameter <T extends NodeModel> of the type NodeView<T>

        at nl.esciencecenter.e3dchem.kripodb.fragmentsbysimilarity.FragmentBySimilarityFactory.<init>(FragmentBySimilarityFactory.java:11)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at java.lang.Class.newInstance(Class.java:442)
        at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:184)
        at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:905)
        at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:243)
        at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:55)
        at org.knime.workbench.repository.RepositoryFactory.createNode(RepositoryFactory.java:116)
        ... 6 more

```

**Comment by sverhoeven** [comment]
After clearing build enviroment, the error disappeared.
